### PR TITLE
Remove `data` directory

### LINKED ISSUE #366: Migrate input data to separate repository
It should be decoupled from the Health-GPS version.

### PR DESCRIPTION
**Pull request by alexdewar**
This data has now been moved to the healthgps-data repo.

Once we have updated the healthgps-examples repo so that all the examples contain the URLs for the data source (https://github.com/imperialCHEPI/healthgps-examples/pull/11), I think we're finally ready to delete the `data` directory in this repo!

There are still a couple of related documentation issues open (#472 and #473) but I don't think these should stand in the way of us nuking >300k lines of code :stuck_out_tongue: 

Closes #366.

### CODE REVIEW

**Comment by alexdewar** [comment]
It turns out this breaks everything :upside_down_face:. I've converted it to draft for now and I'll give it another go.

**Review by SaranjeetKaur — COMMENTED** [review]
That's a lot of stuff!

**Comment by TinyMarsh** [comment]
image

😮

**Comment by jamesturner246** [comment]
Holy smokes! that's a lot of bloat loss... :astonished:

**Comment by alexdewar** [comment]
If only it didn't break everything :stuck_out_tongue:. I'll have a go at fixing this next week. I guess we just need to download a data source when we're configuring things with CMake (only if the tests are being built, though).

**Comment by alexdewar** [comment]
Ok, so the CI is failing because the `clang-tidy` workflow can't handle a diff this big! No matter that most of the diff isn't C++ code.... Anyway, I guess we can always just bypass branch protections when we want to merge.

**Comment by alexdewar** [comment]
I've fixed the failing tests though. Now the test data is downloaded with CMake when you configure the project.

**Review by jamesturner246 — APPROVED** [review]
Bye data. LGTM! :+1:

**Pull request merged**
